In [1]:
import pandas as pd

import numpy as np

In [7]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])
x = np.array([1, 2, 3, 4, 5])
# addition 
print(u + v)

# subtraction 
print(u - v)

# scalar multiplication 
print(2 * v)

[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


In [3]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [4]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [9]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [11]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
])
inv_1 = np.linalg.inv(V)
inv_1

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

Intro to pandas

In [15]:
import pandas as pd

In [16]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [19]:
df_test1 = pd.DataFrame(data,
             columns=columns)

In [20]:
make_series = pd.Series(df_test1['Make'])

In [22]:
df_test1

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [24]:
def convert_to_euros(val):
    return val * 1.609

In [25]:
msrP_eu_1 = df_test1['MSRP'].apply(convert_to_euros)

In [27]:
type(msrP_eu_1)

pandas.core.series.Series

In [30]:
df_test1.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
df_test1.index = ['a', 'b', 'c', 'd', 'e']
df_test1

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [33]:
df_test1.loc[['c']]

Make  Model  Year  Engine HP  Engine Cylinders Transmission Type  \
c  Lotus  Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
c   convertible  54990

In [35]:
df_test1.iloc[[2]]

Make  Model  Year  Engine HP  Engine Cylinders Transmission Type  \
c  Lotus  Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
c   convertible  54990

In [36]:
df_test1.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [37]:
pd.__version__

'2.3.2'

In [38]:
hw_data = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [40]:
hw_data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [41]:
len(hw_data)

9704

In [43]:
len(hw_data.fuel_type.unique())

2

In [44]:
hw_data.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [47]:
hw_data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [50]:
filter = hw_data['origin']=='Asia'
max(hw_data[filter].fuel_efficiency_mpg)

23.759122836520497

In [51]:
hw_data['horsepower'].median()

149.0

In [53]:
hw_data['horsepower'] = hw_data['horsepower'].fillna(hw_data['horsepower'].median())

In [54]:
hw_data['horsepower'].median()

149.0

In [55]:
hw_data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [56]:
asia_cars = hw_data[hw_data['origin'] == 'Asia']

In [58]:
asia_cars[['vehicle_weight','model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [59]:
asia_cars[['vehicle_weight','model_year']][0:7]

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [60]:
asia_7_np =asia_cars[['vehicle_weight','model_year']][0:7].to_numpy()

In [61]:
asia_7_np

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [62]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [63]:
X_t = x.transpose()

In [64]:
XTX = matrix_matrix_multiplication(asia_7_np,asia_7_np.transpose())

In [65]:
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [66]:
XTX_inv = np.linalg.inv(XTX)

In [67]:
XTX_inv

array([[ 6.27784782e+08,  4.52348582e+08, -5.52589667e+08,
        -5.04518657e+08, -1.36497506e+08, -9.70745174e+07,
         2.07769569e+08],
       [ 6.52427761e+08,  1.18496810e+09, -8.15933475e+08,
        -7.54720098e+08, -7.08834488e+08,  2.53306835e+08,
         1.86771033e+08],
       [-4.82034184e+08, -5.85397198e+08,  3.79915957e+08,
         6.66310906e+08,  1.18051009e+08, -1.47095872e+08,
         5.16329750e+07],
       [-4.86725764e+08, -5.86851309e+08,  7.06448581e+08,
         6.82137781e+08,  2.06347119e+08, -3.29606193e+08,
        -1.88697388e+08],
       [-2.37576087e+08, -7.37561522e+08,  2.26902495e+08,
         2.89910408e+08,  1.50145296e+08,  3.48995157e+08,
        -4.08718420e+07],
       [-2.28618838e+08,  1.97697960e+08, -2.05812130e+07,
        -2.25519129e+08,  3.60824331e+08, -2.92220029e+06,
        -8.08263491e+07],
       [ 1.52870693e+08,  7.43387198e+07,  7.67225188e+07,
        -1.51179749e+08,  9.23761238e+06, -2.62872552e+07,
        -1.3533841

In [68]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [69]:
X = asia_7_np

In [71]:
w1 = matrix_matrix_multiplication(X.transpose(),XTX_inv)

In [83]:
print(w1)

[[ 0.00085449  0.00152588 -0.00042725 -0.00146484 -0.0007782  -0.00013733
   0.00048828]
 [-0.00012207 -0.00149536  0.00076294  0.00189209  0.00053024  0.00029755
  -0.00067139]]


In [73]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [89]:
w = matrix_matrix_multiplication(w1,y)

IndexError: tuple index out of range

In [88]:
w1.transpose().shape[1]

2

In [85]:
y.shape[0]

7